### ISSUE TITLE
input file duplicate lines stop processing

### ISSUE THREAD

**Issue by demanasta** [DSOlab/StrainTool#66]
**Describe the bug**
input file duplicate lines stop processing

**Propose**
-- Add README warning
-- add check check on I/O parse script??

**Comment by xanthospap** [comment]
Quite a few funny things happen when we have duplicate lines!!!

So, here is how we are fixing this:
When parsing the stations from the input file via the function `parse_ascii_input`, we are (for each new station) checking that the new station parsed is **NOT** a duplicate (aka already in the list). This check is twofold, that is
1. we check that there is not other station already parsed with the same name, and
2. we check that there is not other station already parsed with the same longitude and latitude values
If either 1 or 2 hold, then we throw (a ValueError) and the program terminates.

Files changed:
1. `pystrain/pystrain/iotools/iparser.py`

**Bug fixed in branch bug65**

**Comment by xanthospap** [comment]
Btw, i think we do not need to add anything to the README file. It is the user's duty to not have ill-formed, ambiguous data files. We cannot guard against everything. Having duplicate data is an error, we do not need to explicitly tell.
@demanasta validate and merge.
